# # Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Louis van Rooyen
title: Electronics Engineer
email: vanrooyenl@outlook.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: louis-van-rooyen
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Stage Zero
  icon: fas fa-globe
  url: https://stagezero.co.za/
- title: iGrid
  icon: fas fa-globe
  url: https://www.igrid.co.za/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, my name's Louis and I am an electronics engineer with a background in Electric and Electronic Engineering. I specialize in robotics and embedded systems. I have a strong passion for problem-solving and have developed expertise in data analysis, system testing, and prototyping. 

  I am most skilled in: <mark>Embedded Software Development (Python, C++)</mark>, <mark>PCB Design</mark>, and <mark>IoT/LoRa Technology</mark>.

content:
  - title: Projects 
    layout: list 
    content:
      - layout: top-middle
        title: Remote Event Tracking System
        link: github.com/sproogen
        additional_links:
          - title: Thesis Project
            icon: fab fa-github
            url: github.com/sproogen/project
        quote: >
          A remote event tracking system using LoRa technology that improved the efficiency of data collection and transmission.
        description: |
          I designed and implemented a remote event tracking system as my thesis project. It used a Raspberry Pi gateway and ESP32 node, programmed in Python and C++, with a custom dashboard built in Plotly and Dash. It involved field tests, custom PCB development, and Matlab-based coverage analysis.

  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: Stage Zero
        link: https://stagezero.co.za/
        sub_title: Electronics Engineer
        caption: February 2024 - Present
        description: |
            As part of the verification team, I design, build, and implement unit system tests on the production line. I’m also involved in redesigning Test Jigs for production with custom PCBs and Raspberry Pi integration, increasing efficiency.

      - layout: left
        title: SmartGrid Technologies (Pty) Ltd
        link: https://www.igrid.co.za/
        sub_title: Engineering Intern
        caption: February 2021 - February 2020
        description: |
          As an intern, I supported the R&D team with lab setup, prototype assembly, and field trials. I led the development of a magnetic pulse sensor test jig, automated data consolidation using Python, and successfully managed production for 1000 units under tight deadlines.

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Stellenbosch University
        caption: 2016 - 2023
        sub_title: BEng Electric and Electronic Engineering
        description: |
          During my time at Stellenbosch University, I completed key courses in control systems, signal processing, and embedded systems. I was a member of the *Harvard Mountaineering Club*, where I held leadership roles such as *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | 
      Aside from my engineering expertise, I am passionate about:
      - Rock climbing
      - Gaming
      - Robotics

# Footer
footer_show_references: true
